# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loplat PlengiTools' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for loplat PlengiTools

  pod 'MiniPlengi'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Sparrow/Modules/RequestPermission', :git => 'https://github.com/IvanVorobei/Sparrow.git'
  pod 'CircleMenu'
  pod 'PopupDialog', '~> 0.7'
end
