# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loplat SDK Sample for Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for loplat SDK Sample for Swift
  pod 'SnapKit', '~> 4.0.0'
  pod 'Bohr'
  pod 'PopupDialog'
  pod 'MiniPlengi', '1.2.6'
end
